version: "3"
services:
  web:
    container_name: ringoyaki-web
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run start"
    ports:
      - 3000:3000
